apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "pvc-ml-ceph-filesystem"
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  