apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "pvc-ml-longhorn"
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  
